# -*- coding: utf-8 -*-
"""064_Krisdayanti_POSTTEST2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eD1jvmGcnqya-JTPWYZMnUTr6IqFI0nQ
"""

#Program Konversi Suhu Dari Celcius ke Fahrenheit, Kelvin dan Reamur

print('Konversi suhu dari skala Celcius ke skala Fahrenheit, Kelvin dan Reamur')
Skala_Celcius = float (input('Masukan suhu dalam skala Celcius : '))
Skala_Fahrenheit = (9. / 5)* Skala_Celcius + 32
Skala_Kelvin = 273.15 + Skala_Celcius
Skala_Reamur = (4. / 5)* Skala_Celcius
print('Hasil dari konversi suhu dalam skala Celcius ke Skala Fahrenheit, Kelvin dan Reamur adalah sebagai berikut: ')
print('Suhu dalam skala Celcius adalah : %f derajat' % (Skala_Celcius))
print('Suhu dalam skala Celcius ke skala Fahrenheit adalah : %2f F' % (Skala_Fahrenheit))
print('Suhu dalam skala Celcius ke skala Kelvin adalah : %f K' % (Skala_Kelvin))
print('Suhu dalam skala Celcius ke skala Reamur adalah : %f R' % (Skala_Reamur))

#Inputan data dengan Tema BENDA (Jacket)

Jacket = input("Ada berapa jacket yang kamu miliki? : ")
Warna_jacket = input("Jacket warna apa yang paling kamu sukai? : ")
Mine = input("Jika seseorang meminjam jacket kesayanganmu, akankah kamu meminjamkannya? : ")
Gift = input("Pernahkah kamu mendapatkan jacket sebagai hadiah? : ")
Wearing = input("Apakah kamu suka memakai jacket saat bepergian atau keluar rumah? : ")

list = []
list.append(Jacket)
list.append(Warna_jacket)
list.append(Mine)
list.append(Gift)
list.append(Wearing)

print(list[0])
print(list[1])
print(list[2])
print(list[3])
print(list[4])
print("Variabel Jacket          : ", Jacket,        "tipe data : ", type (Jacket),        end="\n\n")
print("Variabel Warna_jacket    : ", Warna_jacket,  "tipe data : ", type (Warna_jacket),  end="\n\n")
print("Variabel Mine            : ", Mine,          "tipe data : ", type (Mine),          end="\n\n")
print("Variabel Gift            : ", Gift,          "tipe data : ", type (Gift),          end="\n\n")
print("Variabel Wearing         : ", Wearing,       "tipe data : ", type (Wearing),       end="\n\n")